// @ts-nocheck
/**
 * This file is generated by a tool. Do not edit directly.
 * Generated by openapi-angular-generator.
 */
/** Document-level OpenAPI/Swagger metadata captured from the source spec. */
export interface ApiDocumentMeta {
	openapi?: string;
	swagger?: string;
	$self?: string;
	jsonSchemaDialect?: string;
	/** Top-level specification extensions (x-*) preserved for reverse generation. */
	extensions?: Record<
		string,
		string | number | boolean | object | undefined | null
	>;
}

/** OpenAPI document metadata used for reverse generation. */
export const API_DOCUMENT_META: ApiDocumentMeta = {
	swagger: "2.0",
};
