// @ts-nocheck
/**
 * This file is generated by a tool. Do not edit directly.
 * Generated by openapi-angular-generator.
 */
/** Contact information for the API (OAS Contact Object). */
export interface ApiContact {
	[key: string]: string | number | boolean | object | undefined | null;
	name?: string;
	url?: string;
	email?: string;
}

/** License metadata for the API (OAS License Object). */
export interface ApiLicense {
	[key: string]: string | number | boolean | object | undefined | null;
	name: string;
	url?: string;
	identifier?: string;
}

/** External documentation metadata (OAS External Documentation Object). */
export interface ApiExternalDocs {
	[key: string]: string | number | boolean | object | undefined | null;
	description?: string;
	url: string;
}

/** Interface representing the metadata of the API. */
export interface ApiInfo {
	[key: string]: string | number | boolean | object | undefined | null;
	title: string;
	version: string;
	description?: string;
	/** Short summary of the API (OAS 3.1+). */
	summary?: string;
	termsOfService?: string;
	contact?: ApiContact;
	license?: ApiLicense;
}

/** Interface representing a tag defined in the API. */
export interface ApiTag {
	[key: string]: string | number | boolean | object | undefined | null;
	name: string;
	description?: string;
	/** Short summary of the tag (OAS 3.1+). */
	summary?: string;
	/** Parent tag naming for grouping (Extensions). */
	parent?: string;
	/** Tag categorization (Extensions). */
	kind?: string;
	externalDocs?: ApiExternalDocs;
}

/** Metadata about the API defined in the OpenAPI specification. */
export const API_INFO: ApiInfo = {
	description:
		"This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.",
	version: "1.0.7",
	title: "Swagger Petstore",
	termsOfService: "http://swagger.io/terms/",
	contact: {
		email: "apiteam@swagger.io",
	},
	license: {
		name: "Apache 2.0",
		url: "http://www.apache.org/licenses/LICENSE-2.0.html",
	},
};
/** List of tags defined in the OpenAPI specification. */
export const API_TAGS: ApiTag[] = [
	{
		name: "pet",
		description: "Everything about your Pets",
		externalDocs: {
			description: "Find out more",
			url: "http://swagger.io",
		},
	},
	{
		name: "store",
		description: "Access to Petstore orders",
	},
	{
		name: "user",
		description: "Operations about user",
		externalDocs: {
			description: "Find out more about our store",
			url: "http://swagger.io",
		},
	},
];
/** Global external documentation defined in the OpenAPI specification. */
export const API_EXTERNAL_DOCS: ApiExternalDocs | undefined = {
	description: "Find out more about Swagger",
	url: "http://swagger.io",
};
