// @ts-nocheck
/**
* This file is generated by a tool. Do not edit directly.
* Generated by openapi-angular-generator.
*/
/** OpenAPI Security Requirement object shape. */
export type ApiSecurityRequirement = Record<string, string[]>;

/** The Security Schemes defined in the OpenAPI specification. */
export const API_SECURITY_SCHEMES = {
    "api_key": {
        "type": "apiKey",
        "name": "api_key",
        "in": "header"
    },
    "petstore_auth": {
        "type": "oauth2",
        "authorizationUrl": "https://petstore.swagger.io/oauth/authorize",
        "flow": "implicit",
        "scopes": {
            "read:pets": "read your pets",
            "write:pets": "modify pets in your account"
        }
    }
};
