// @ts-nocheck
/**
* This file is generated by a tool. Do not edit directly.
* Generated by openapi-angular-generator.
*/
/** The servers defined in the OpenAPI specification. */
export const API_SERVERS = [
    {
        "url": "https://petstore.swagger.io/v2"
    },
    {
        "url": "http://petstore.swagger.io/v2"
    }
];
