// @ts-nocheck
/**
 * This file is generated by a tool. Do not edit directly.
 * Generated by openapi-angular-generator.
 */

/** List of API Tags with metadata. */
export const API_TAGS = [
	{
		name: "pet",
		description: "Everything about your Pets",
		externalDocs: {
			description: "Find out more",
			url: "http://swagger.io",
		},
	},
	{
		name: "store",
		description: "Access to Petstore orders",
	},
	{
		name: "user",
		description: "Operations about user",
		externalDocs: {
			description: "Find out more about our store",
			url: "http://swagger.io",
		},
	},
];
/** Lookup map for API Tags by name. */
export const API_TAGS_MAP = {
	pet: {
		name: "pet",
		description: "Everything about your Pets",
		externalDocs: {
			description: "Find out more",
			url: "http://swagger.io",
		},
	},
	store: {
		name: "store",
		description: "Access to Petstore orders",
	},
	user: {
		name: "user",
		description: "Operations about user",
		externalDocs: {
			description: "Find out more about our store",
			url: "http://swagger.io",
		},
	},
};
