/**
 * Utility for building React TSX/JSX UI elements securely.
 */
export class ReactElementBuilder {
    /**
     * Builds a basic React component wrapper structure with hooks support.
     * @param componentName The pascal-cased component name.
     * @param imports The required import statements.
     * @param body The hook logic and state setup inside the component.
     * @param render The children JSX content string.
     * @returns A string representing the functional component.
     */
    public static buildFunctionalComponent(
        componentName: string,
        imports: string[],
        body: string,
        render: string,
    ): string {
        const importsStr = imports.join('\n');
        return `${importsStr}\n\n/**\n * ${componentName} component.\n * Auto-generated by CDD-TS.\n */\nexport const ${componentName} = () => {\n${body}\n    return (\n        <div className="${componentName.toLowerCase()}-container">\n${render}\n        </div>\n    );\n};\n`;
    }

    /**
     * Builds an HTML input element string for React with a11y and i18n support.
     * @param name The name of the input.
     * @param type The HTML input type.
     * @param required Indicates if the input is required for aria-required.
     * @returns The JSX string for the input.
     */
    public static buildInput(name: string, type: string = 'text', required: boolean = false): string {
        const requiredAttr = required ? ' required aria-required="true"' : '';
        return `            <div className="form-group">\n                <label htmlFor="${name}">{t('field.${name}', '${name}')}</label>\n                <input type="${type}" id="${name}" name="${name}" defaultValue=""${requiredAttr} />\n            </div>`;
    }
}
