/**
* This file is generated by a tool. Do not edit directly.
* Generated by openapi-angular-generator.
*/
import * as http from "node:http";
import * as https from "node:https";
import { URL } from "node:url";
import { ParameterSerializer } from "../utils/parameter-serializer";
import { getServerUrl, resolveServerUrl } from "../utils/server-url";
import { ApiResponse, Pet } from "../models";

export class PetService {
    private basePath = "";

    constructor(basePath?: string) {
        this.basePath = basePath || getServerUrl(0, {});
    }

    async uploadFile(petId: number, additionalMetadata?: string, file?: File, options?: import('node:http').RequestOptions & { server?: number | string; serverVariables?: Record<string, string> }): Promise<ApiResponse> {
        const basePath = (options?.server !== undefined || options?.serverVariables !== undefined) ? getServerUrl(options?.server ?? 0, options?.serverVariables ?? {}) : this.basePath;
        const url = new URL(`${basePath}/pet/${ParameterSerializer.serializePathParam('petId', petId, 'simple', false, false)}/uploadImage`);
        const headers: Record<string, string> = { ...(options?.headers as Record<string, string>) };
        const formData = new FormData();
        if (additionalMetadata != null) { formData.append('additionalMetadata', additionalMetadata as any); }
        if (file != null) { formData.append('file', file as any); }
        const requestOptions: import('node:http').RequestOptions | import('node:https').RequestOptions = { ...options, method: 'POST', headers };
        return new Promise((resolve, reject) => {
            const client = url.protocol === 'https:' ? https : http;
            const req = client.request(url, requestOptions, (res) => {
                const chunks: Buffer[] = [];
                res.on('data', (chunk) => chunks.push(chunk));
                res.on('end', () => {
                    const buffer = Buffer.concat(chunks);
                    if (res.statusCode && res.statusCode >= 400) {
                        return reject(new Error('Request failed: ' + res.statusCode + ' ' + res.statusMessage));
                    }
                    try {
                        resolve(JSON.parse(buffer.toString('utf-8')));
                    } catch (e) {
                        resolve(buffer.toString('utf-8') as string | number | boolean | object | undefined | null as ApiResponse);
                    }
                });
            });
            req.on('error', reject);
            req.write(formData);
            req.end();
        });
    }

    async addPet(pet: Pet, options?: import('node:http').RequestOptions & { server?: number | string; serverVariables?: Record<string, string> }): Promise<string | number | boolean | object | undefined | null> {
        const basePath = (options?.server !== undefined || options?.serverVariables !== undefined) ? getServerUrl(options?.server ?? 0, options?.serverVariables ?? {}) : this.basePath;
        const url = new URL(`${basePath}/pet`);
        const headers: Record<string, string> = { ...(options?.headers as Record<string, string>) };
        if (!headers['Content-Type']) { headers['Content-Type'] = 'application/json'; }
        const requestOptions: import('node:http').RequestOptions | import('node:https').RequestOptions = { ...options, method: 'POST', headers };
        return new Promise((resolve, reject) => {
            const client = url.protocol === 'https:' ? https : http;
            const req = client.request(url, requestOptions, (res) => {
                const chunks: Buffer[] = [];
                res.on('data', (chunk) => chunks.push(chunk));
                res.on('end', () => {
                    const buffer = Buffer.concat(chunks);
                    if (res.statusCode && res.statusCode >= 400) {
                        return reject(new Error('Request failed: ' + res.statusCode + ' ' + res.statusMessage));
                    }
                    try {
                        resolve(JSON.parse(buffer.toString('utf-8')));
                    } catch (e) {
                        resolve(buffer.toString('utf-8') as string | number | boolean | object | undefined | null as string | number | boolean | object | undefined | null);
                    }
                });
            });
            req.on('error', reject);
            req.write(JSON.stringify(pet));
            req.end();
        });
    }

    async updatePet(pet: Pet, options?: import('node:http').RequestOptions & { server?: number | string; serverVariables?: Record<string, string> }): Promise<string | number | boolean | object | undefined | null> {
        const basePath = (options?.server !== undefined || options?.serverVariables !== undefined) ? getServerUrl(options?.server ?? 0, options?.serverVariables ?? {}) : this.basePath;
        const url = new URL(`${basePath}/pet`);
        const headers: Record<string, string> = { ...(options?.headers as Record<string, string>) };
        if (!headers['Content-Type']) { headers['Content-Type'] = 'application/json'; }
        const requestOptions: import('node:http').RequestOptions | import('node:https').RequestOptions = { ...options, method: 'PUT', headers };
        return new Promise((resolve, reject) => {
            const client = url.protocol === 'https:' ? https : http;
            const req = client.request(url, requestOptions, (res) => {
                const chunks: Buffer[] = [];
                res.on('data', (chunk) => chunks.push(chunk));
                res.on('end', () => {
                    const buffer = Buffer.concat(chunks);
                    if (res.statusCode && res.statusCode >= 400) {
                        return reject(new Error('Request failed: ' + res.statusCode + ' ' + res.statusMessage));
                    }
                    try {
                        resolve(JSON.parse(buffer.toString('utf-8')));
                    } catch (e) {
                        resolve(buffer.toString('utf-8') as string | number | boolean | object | undefined | null as string | number | boolean | object | undefined | null);
                    }
                });
            });
            req.on('error', reject);
            req.write(JSON.stringify(pet));
            req.end();
        });
    }

    async findPetsByStatus(status: ('available' | 'pending' | 'sold')[], options?: import('node:http').RequestOptions & { server?: number | string; serverVariables?: Record<string, string> }): Promise<Pet[]> {
        const basePath = (options?.server !== undefined || options?.serverVariables !== undefined) ? getServerUrl(options?.server ?? 0, options?.serverVariables ?? {}) : this.basePath;
        const url = new URL(`${basePath}/pet/findByStatus`);
        const serialized_status = ParameterSerializer.serializeQueryParam({ "name": "status", "in": "query", "style": "form", "explode": true, "allowReserved": false }, status);
        serialized_status.forEach((entry: { key: string; value: string }) => url.searchParams.append(entry.key, entry.value));
        const headers: Record<string, string> = { ...(options?.headers as Record<string, string>) };
        const requestOptions: import('node:http').RequestOptions | import('node:https').RequestOptions = { ...options, method: 'GET', headers };
        return new Promise((resolve, reject) => {
            const client = url.protocol === 'https:' ? https : http;
            const req = client.request(url, requestOptions, (res) => {
                const chunks: Buffer[] = [];
                res.on('data', (chunk) => chunks.push(chunk));
                res.on('end', () => {
                    const buffer = Buffer.concat(chunks);
                    if (res.statusCode && res.statusCode >= 400) {
                        return reject(new Error('Request failed: ' + res.statusCode + ' ' + res.statusMessage));
                    }
                    try {
                        resolve(JSON.parse(buffer.toString('utf-8')));
                    } catch (e) {
                        resolve(buffer.toString('utf-8') as string | number | boolean | object | undefined | null as Pet[]);
                    }
                });
            });
            req.on('error', reject);
            req.end();
        });
    }

    async findPetsByTags(tags: string[], options?: import('node:http').RequestOptions & { server?: number | string; serverVariables?: Record<string, string> }): Promise<Pet[]> {
        const basePath = (options?.server !== undefined || options?.serverVariables !== undefined) ? getServerUrl(options?.server ?? 0, options?.serverVariables ?? {}) : this.basePath;
        const url = new URL(`${basePath}/pet/findByTags`);
        const serialized_tags = ParameterSerializer.serializeQueryParam({ "name": "tags", "in": "query", "style": "form", "explode": true, "allowReserved": false }, tags);
        serialized_tags.forEach((entry: { key: string; value: string }) => url.searchParams.append(entry.key, entry.value));
        const headers: Record<string, string> = { ...(options?.headers as Record<string, string>) };
        const requestOptions: import('node:http').RequestOptions | import('node:https').RequestOptions = { ...options, method: 'GET', headers };
        return new Promise((resolve, reject) => {
            const client = url.protocol === 'https:' ? https : http;
            const req = client.request(url, requestOptions, (res) => {
                const chunks: Buffer[] = [];
                res.on('data', (chunk) => chunks.push(chunk));
                res.on('end', () => {
                    const buffer = Buffer.concat(chunks);
                    if (res.statusCode && res.statusCode >= 400) {
                        return reject(new Error('Request failed: ' + res.statusCode + ' ' + res.statusMessage));
                    }
                    try {
                        resolve(JSON.parse(buffer.toString('utf-8')));
                    } catch (e) {
                        resolve(buffer.toString('utf-8') as string | number | boolean | object | undefined | null as Pet[]);
                    }
                });
            });
            req.on('error', reject);
            req.end();
        });
    }

    async getPetById(petId: number, options?: import('node:http').RequestOptions & { server?: number | string; serverVariables?: Record<string, string> }): Promise<Pet> {
        const basePath = (options?.server !== undefined || options?.serverVariables !== undefined) ? getServerUrl(options?.server ?? 0, options?.serverVariables ?? {}) : this.basePath;
        const url = new URL(`${basePath}/pet/${ParameterSerializer.serializePathParam('petId', petId, 'simple', false, false)}`);
        const headers: Record<string, string> = { ...(options?.headers as Record<string, string>) };
        const requestOptions: import('node:http').RequestOptions | import('node:https').RequestOptions = { ...options, method: 'GET', headers };
        return new Promise((resolve, reject) => {
            const client = url.protocol === 'https:' ? https : http;
            const req = client.request(url, requestOptions, (res) => {
                const chunks: Buffer[] = [];
                res.on('data', (chunk) => chunks.push(chunk));
                res.on('end', () => {
                    const buffer = Buffer.concat(chunks);
                    if (res.statusCode && res.statusCode >= 400) {
                        return reject(new Error('Request failed: ' + res.statusCode + ' ' + res.statusMessage));
                    }
                    try {
                        resolve(JSON.parse(buffer.toString('utf-8')));
                    } catch (e) {
                        resolve(buffer.toString('utf-8') as string | number | boolean | object | undefined | null as Pet);
                    }
                });
            });
            req.on('error', reject);
            req.end();
        });
    }

    async updatePetWithForm(petId: number, name?: string, status?: string, options?: import('node:http').RequestOptions & { server?: number | string; serverVariables?: Record<string, string> }): Promise<string | number | boolean | object | undefined | null> {
        const basePath = (options?.server !== undefined || options?.serverVariables !== undefined) ? getServerUrl(options?.server ?? 0, options?.serverVariables ?? {}) : this.basePath;
        const url = new URL(`${basePath}/pet/${ParameterSerializer.serializePathParam('petId', petId, 'simple', false, false)}`);
        const headers: Record<string, string> = { ...(options?.headers as Record<string, string>) };
        const formBody = new URLSearchParams();
        if (name != null) { formBody.append('name', String(name)); }
        if (status != null) { formBody.append('status', String(status)); }
        if (!headers['Content-Type']) { headers['Content-Type'] = 'application/x-www-form-urlencoded'; }
        const requestOptions: import('node:http').RequestOptions | import('node:https').RequestOptions = { ...options, method: 'POST', headers };
        return new Promise((resolve, reject) => {
            const client = url.protocol === 'https:' ? https : http;
            const req = client.request(url, requestOptions, (res) => {
                const chunks: Buffer[] = [];
                res.on('data', (chunk) => chunks.push(chunk));
                res.on('end', () => {
                    const buffer = Buffer.concat(chunks);
                    if (res.statusCode && res.statusCode >= 400) {
                        return reject(new Error('Request failed: ' + res.statusCode + ' ' + res.statusMessage));
                    }
                    try {
                        resolve(JSON.parse(buffer.toString('utf-8')));
                    } catch (e) {
                        resolve(buffer.toString('utf-8') as string | number | boolean | object | undefined | null as string | number | boolean | object | undefined | null);
                    }
                });
            });
            req.on('error', reject);
            req.write(formBody.toString());
            req.end();
        });
    }

    async deletePet(petId: number, apiKey?: string, options?: import('node:http').RequestOptions & { server?: number | string; serverVariables?: Record<string, string> }): Promise<string | number | boolean | object | undefined | null> {
        const basePath = (options?.server !== undefined || options?.serverVariables !== undefined) ? getServerUrl(options?.server ?? 0, options?.serverVariables ?? {}) : this.basePath;
        const url = new URL(`${basePath}/pet/${ParameterSerializer.serializePathParam('petId', petId, 'simple', false, false)}`);
        const headers: Record<string, string> = { ...(options?.headers as Record<string, string>) };
        if (apiKey != null) { headers['api_key'] = ParameterSerializer.serializeHeaderParam(apiKey, false); }
        const requestOptions: import('node:http').RequestOptions | import('node:https').RequestOptions = { ...options, method: 'DELETE', headers };
        return new Promise((resolve, reject) => {
            const client = url.protocol === 'https:' ? https : http;
            const req = client.request(url, requestOptions, (res) => {
                const chunks: Buffer[] = [];
                res.on('data', (chunk) => chunks.push(chunk));
                res.on('end', () => {
                    const buffer = Buffer.concat(chunks);
                    if (res.statusCode && res.statusCode >= 400) {
                        return reject(new Error('Request failed: ' + res.statusCode + ' ' + res.statusMessage));
                    }
                    try {
                        resolve(JSON.parse(buffer.toString('utf-8')));
                    } catch (e) {
                        resolve(buffer.toString('utf-8') as string | number | boolean | object | undefined | null as string | number | boolean | object | undefined | null);
                    }
                });
            });
            req.on('error', reject);
            req.end();
        });
    }
}

export type AddPetError = string | number | boolean | object | undefined | null;
export type UpdatePetError = string | number | boolean | object | undefined | null;
export type FindPetsByStatusError = string | number | boolean | object | undefined | null;
export type FindPetsByTagsError = string | number | boolean | object | undefined | null;
export type GetPetByIdError = string | number | boolean | object | undefined | null;
export type UpdatePetWithFormError = string | number | boolean | object | undefined | null;
export type DeletePetError = string | number | boolean | object | undefined | null;
