/**
 * This file is generated by a tool. Do not edit directly.
 * Generated by openapi-angular-generator.
 */
import * as http from "node:http";
import * as https from "node:https";
import { URL } from "node:url";
import type { Order } from "../models";
import { ParameterSerializer } from "../utils/parameter-serializer";
import { getServerUrl, resolveServerUrl } from "../utils/server-url";

export class StoreService {
	private basePath = "";

	constructor(basePath?: string) {
		this.basePath = basePath || getServerUrl(0, {});
	}

	async getInventory(
		options?: import("node:http").RequestOptions & {
			server?: number | string;
			serverVariables?: Record<string, string>;
		},
	): Promise<{ [key: string]: number }> {
		const basePath =
			options?.server !== undefined || options?.serverVariables !== undefined
				? getServerUrl(options?.server ?? 0, options?.serverVariables ?? {})
				: this.basePath;
		const url = new URL(`${basePath}/store/inventory`);
		const headers: Record<string, string> = {
			...(options?.headers as Record<string, string>),
		};
		const requestOptions:
			| import("node:http").RequestOptions
			| import("node:https").RequestOptions = {
			...options,
			method: "GET",
			headers,
		};
		return new Promise(async (resolve, reject) => {
			const client = url.protocol === "https:" ? https : http;
			const req = client.request(url, requestOptions, (res) => {
				const chunks: Buffer[] = [];
				res.on("data", (chunk) => chunks.push(chunk));
				res.on("end", () => {
					const buffer = Buffer.concat(chunks);
					if (res.statusCode && res.statusCode >= 400) {
						return reject(
							new Error(
								`Request failed: ${res.statusCode} ${res.statusMessage}`,
							),
						);
					}
					try {
						resolve(JSON.parse(buffer.toString("utf-8")));
					} catch (_e) {
						resolve(
							buffer.toString("utf-8") as
								| string
								| number
								| boolean
								| object
								| undefined
								| null as { [key: string]: number },
						);
					}
				});
			});
			req.on("error", reject);
			req.end();
		});
	}

	async placeOrder(
		order: Order,
		options?: import("node:http").RequestOptions & {
			server?: number | string;
			serverVariables?: Record<string, string>;
		},
	): Promise<Order> {
		const basePath =
			options?.server !== undefined || options?.serverVariables !== undefined
				? getServerUrl(options?.server ?? 0, options?.serverVariables ?? {})
				: this.basePath;
		const url = new URL(`${basePath}/store/order`);
		const headers: Record<string, string> = {
			...(options?.headers as Record<string, string>),
		};
		const requestData = JSON.stringify(order);
		if (!headers["Content-Type"]) {
			headers["Content-Type"] = "application/json";
		}
		if (!headers["Content-Length"]) {
			headers["Content-Length"] = Buffer.byteLength(requestData).toString();
		}
		const requestOptions:
			| import("node:http").RequestOptions
			| import("node:https").RequestOptions = {
			...options,
			method: "POST",
			headers,
		};
		return new Promise(async (resolve, reject) => {
			const client = url.protocol === "https:" ? https : http;
			const req = client.request(url, requestOptions, (res) => {
				const chunks: Buffer[] = [];
				res.on("data", (chunk) => chunks.push(chunk));
				res.on("end", () => {
					const buffer = Buffer.concat(chunks);
					if (res.statusCode && res.statusCode >= 400) {
						return reject(
							new Error(
								`Request failed: ${res.statusCode} ${res.statusMessage}`,
							),
						);
					}
					try {
						resolve(JSON.parse(buffer.toString("utf-8")));
					} catch (_e) {
						resolve(
							buffer.toString("utf-8") as
								| string
								| number
								| boolean
								| object
								| undefined
								| null as Order,
						);
					}
				});
			});
			req.on("error", reject);
			req.write(requestData);
			req.end();
		});
	}

	async getOrderById(
		orderId: number,
		options?: import("node:http").RequestOptions & {
			server?: number | string;
			serverVariables?: Record<string, string>;
		},
	): Promise<Order> {
		const basePath =
			options?.server !== undefined || options?.serverVariables !== undefined
				? getServerUrl(options?.server ?? 0, options?.serverVariables ?? {})
				: this.basePath;
		const url = new URL(
			`${basePath}/store/order/${ParameterSerializer.serializePathParam("orderId", orderId, "simple", false, false)}`,
		);
		const headers: Record<string, string> = {
			...(options?.headers as Record<string, string>),
		};
		const requestOptions:
			| import("node:http").RequestOptions
			| import("node:https").RequestOptions = {
			...options,
			method: "GET",
			headers,
		};
		return new Promise(async (resolve, reject) => {
			const client = url.protocol === "https:" ? https : http;
			const req = client.request(url, requestOptions, (res) => {
				const chunks: Buffer[] = [];
				res.on("data", (chunk) => chunks.push(chunk));
				res.on("end", () => {
					const buffer = Buffer.concat(chunks);
					if (res.statusCode && res.statusCode >= 400) {
						return reject(
							new Error(
								`Request failed: ${res.statusCode} ${res.statusMessage}`,
							),
						);
					}
					try {
						resolve(JSON.parse(buffer.toString("utf-8")));
					} catch (_e) {
						resolve(
							buffer.toString("utf-8") as
								| string
								| number
								| boolean
								| object
								| undefined
								| null as Order,
						);
					}
				});
			});
			req.on("error", reject);
			req.end();
		});
	}

	async deleteOrder(
		orderId: number,
		options?: import("node:http").RequestOptions & {
			server?: number | string;
			serverVariables?: Record<string, string>;
		},
	): Promise<string | number | boolean | object | undefined | null> {
		const basePath =
			options?.server !== undefined || options?.serverVariables !== undefined
				? getServerUrl(options?.server ?? 0, options?.serverVariables ?? {})
				: this.basePath;
		const url = new URL(
			`${basePath}/store/order/${ParameterSerializer.serializePathParam("orderId", orderId, "simple", false, false)}`,
		);
		const headers: Record<string, string> = {
			...(options?.headers as Record<string, string>),
		};
		const requestOptions:
			| import("node:http").RequestOptions
			| import("node:https").RequestOptions = {
			...options,
			method: "DELETE",
			headers,
		};
		return new Promise(async (resolve, reject) => {
			const client = url.protocol === "https:" ? https : http;
			const req = client.request(url, requestOptions, (res) => {
				const chunks: Buffer[] = [];
				res.on("data", (chunk) => chunks.push(chunk));
				res.on("end", () => {
					const buffer = Buffer.concat(chunks);
					if (res.statusCode && res.statusCode >= 400) {
						return reject(
							new Error(
								`Request failed: ${res.statusCode} ${res.statusMessage}`,
							),
						);
					}
					try {
						resolve(JSON.parse(buffer.toString("utf-8")));
					} catch (_e) {
						resolve(
							buffer.toString("utf-8") as
								| string
								| number
								| boolean
								| object
								| undefined
								| null as string | number | boolean | object | undefined | null,
						);
					}
				});
			});
			req.on("error", reject);
			req.end();
		});
	}
}

export type PlaceOrderError =
	| string
	| number
	| boolean
	| object
	| undefined
	| null;
export type GetOrderByIdError =
	| string
	| number
	| boolean
	| object
	| undefined
	| null;
export type DeleteOrderError =
	| string
	| number
	| boolean
	| object
	| undefined
	| null;
