/**
 * This file is generated by a tool. Do not edit directly.
 * Generated by openapi-angular-generator.
 */
import * as http from "node:http";
import * as https from "node:https";
import { URL } from "node:url";
import { ParameterSerializer } from "../utils/parameter-serializer";
import { getServerUrl, resolveServerUrl } from "../utils/server-url";
import type { User } from "../models";

export class UserService {
	private basePath = "";

	constructor(basePath?: string) {
		this.basePath = basePath || getServerUrl(0, {});
	}

	async createUsersWithListInput(
		user: User[],
		options?: import("node:http").RequestOptions & {
			server?: number | string;
			serverVariables?: Record<string, string>;
		},
	): Promise<User[]> {
		const basePath =
			options?.server !== undefined || options?.serverVariables !== undefined
				? getServerUrl(options?.server ?? 0, options?.serverVariables ?? {})
				: this.basePath;
		const url = new URL(`${basePath}/user/createWithList`);
		const headers: Record<string, string> = {
			...(options?.headers as Record<string, string>),
		};
		const requestData = JSON.stringify(user);
		if (!headers["Content-Type"]) {
			headers["Content-Type"] = "application/json";
		}
		if (!headers["Content-Length"]) {
			headers["Content-Length"] = Buffer.byteLength(requestData).toString();
		}
		const requestOptions:
			| import("node:http").RequestOptions
			| import("node:https").RequestOptions = {
			...options,
			method: "POST",
			headers,
		};
		return new Promise(async (resolve, reject) => {
			const client = url.protocol === "https:" ? https : http;
			const req = client.request(url, requestOptions, (res) => {
				const chunks: Buffer[] = [];
				res.on("data", (chunk) => chunks.push(chunk));
				res.on("end", () => {
					const buffer = Buffer.concat(chunks);
					if (res.statusCode && res.statusCode >= 400) {
						return reject(
							new Error(
								`Request failed: ${res.statusCode} ${res.statusMessage}`,
							),
						);
					}
					try {
						resolve(JSON.parse(buffer.toString("utf-8")));
					} catch (_e) {
						resolve(
							buffer.toString("utf-8") as
								| string
								| number
								| boolean
								| object
								| undefined
								| null as User[],
						);
					}
				});
			});
			req.on("error", reject);
			req.write(requestData);
			req.end();
		});
	}

	async getUserByName(
		username: string,
		options?: import("node:http").RequestOptions & {
			server?: number | string;
			serverVariables?: Record<string, string>;
		},
	): Promise<User> {
		const basePath =
			options?.server !== undefined || options?.serverVariables !== undefined
				? getServerUrl(options?.server ?? 0, options?.serverVariables ?? {})
				: this.basePath;
		const url = new URL(
			`${basePath}/user/${ParameterSerializer.serializePathParam("username", username, "simple", false, false)}`,
		);
		const headers: Record<string, string> = {
			...(options?.headers as Record<string, string>),
		};
		const requestOptions:
			| import("node:http").RequestOptions
			| import("node:https").RequestOptions = {
			...options,
			method: "GET",
			headers,
		};
		return new Promise(async (resolve, reject) => {
			const client = url.protocol === "https:" ? https : http;
			const req = client.request(url, requestOptions, (res) => {
				const chunks: Buffer[] = [];
				res.on("data", (chunk) => chunks.push(chunk));
				res.on("end", () => {
					const buffer = Buffer.concat(chunks);
					if (res.statusCode && res.statusCode >= 400) {
						return reject(
							new Error(
								`Request failed: ${res.statusCode} ${res.statusMessage}`,
							),
						);
					}
					try {
						resolve(JSON.parse(buffer.toString("utf-8")));
					} catch (_e) {
						resolve(
							buffer.toString("utf-8") as
								| string
								| number
								| boolean
								| object
								| undefined
								| null as User,
						);
					}
				});
			});
			req.on("error", reject);
			req.end();
		});
	}

	async updateUser(
		username: string,
		user: User,
		options?: import("node:http").RequestOptions & {
			server?: number | string;
			serverVariables?: Record<string, string>;
		},
	): Promise<string | number | boolean | object | undefined | null> {
		const basePath =
			options?.server !== undefined || options?.serverVariables !== undefined
				? getServerUrl(options?.server ?? 0, options?.serverVariables ?? {})
				: this.basePath;
		const url = new URL(
			`${basePath}/user/${ParameterSerializer.serializePathParam("username", username, "simple", false, false)}`,
		);
		const headers: Record<string, string> = {
			...(options?.headers as Record<string, string>),
		};
		const requestData = JSON.stringify(user);
		if (!headers["Content-Type"]) {
			headers["Content-Type"] = "application/json";
		}
		if (!headers["Content-Length"]) {
			headers["Content-Length"] = Buffer.byteLength(requestData).toString();
		}
		const requestOptions:
			| import("node:http").RequestOptions
			| import("node:https").RequestOptions = {
			...options,
			method: "PUT",
			headers,
		};
		return new Promise(async (resolve, reject) => {
			const client = url.protocol === "https:" ? https : http;
			const req = client.request(url, requestOptions, (res) => {
				const chunks: Buffer[] = [];
				res.on("data", (chunk) => chunks.push(chunk));
				res.on("end", () => {
					const buffer = Buffer.concat(chunks);
					if (res.statusCode && res.statusCode >= 400) {
						return reject(
							new Error(
								`Request failed: ${res.statusCode} ${res.statusMessage}`,
							),
						);
					}
					try {
						resolve(JSON.parse(buffer.toString("utf-8")));
					} catch (_e) {
						resolve(
							buffer.toString("utf-8") as
								| string
								| number
								| boolean
								| object
								| undefined
								| null as string | number | boolean | object | undefined | null,
						);
					}
				});
			});
			req.on("error", reject);
			req.write(requestData);
			req.end();
		});
	}

	async deleteUser(
		username: string,
		options?: import("node:http").RequestOptions & {
			server?: number | string;
			serverVariables?: Record<string, string>;
		},
	): Promise<string | number | boolean | object | undefined | null> {
		const basePath =
			options?.server !== undefined || options?.serverVariables !== undefined
				? getServerUrl(options?.server ?? 0, options?.serverVariables ?? {})
				: this.basePath;
		const url = new URL(
			`${basePath}/user/${ParameterSerializer.serializePathParam("username", username, "simple", false, false)}`,
		);
		const headers: Record<string, string> = {
			...(options?.headers as Record<string, string>),
		};
		const requestOptions:
			| import("node:http").RequestOptions
			| import("node:https").RequestOptions = {
			...options,
			method: "DELETE",
			headers,
		};
		return new Promise(async (resolve, reject) => {
			const client = url.protocol === "https:" ? https : http;
			const req = client.request(url, requestOptions, (res) => {
				const chunks: Buffer[] = [];
				res.on("data", (chunk) => chunks.push(chunk));
				res.on("end", () => {
					const buffer = Buffer.concat(chunks);
					if (res.statusCode && res.statusCode >= 400) {
						return reject(
							new Error(
								`Request failed: ${res.statusCode} ${res.statusMessage}`,
							),
						);
					}
					try {
						resolve(JSON.parse(buffer.toString("utf-8")));
					} catch (_e) {
						resolve(
							buffer.toString("utf-8") as
								| string
								| number
								| boolean
								| object
								| undefined
								| null as string | number | boolean | object | undefined | null,
						);
					}
				});
			});
			req.on("error", reject);
			req.end();
		});
	}

	async loginUser(
		username: string,
		password: string,
		options?: import("node:http").RequestOptions & {
			server?: number | string;
			serverVariables?: Record<string, string>;
		},
	): Promise<string> {
		const basePath =
			options?.server !== undefined || options?.serverVariables !== undefined
				? getServerUrl(options?.server ?? 0, options?.serverVariables ?? {})
				: this.basePath;
		const url = new URL(`${basePath}/user/login`);
		const serialized_username = ParameterSerializer.serializeQueryParam(
			{
				name: "username",
				in: "query",
				style: "form",
				explode: true,
				allowReserved: false,
			},
			username,
		);
		serialized_username.forEach((entry: { key: string; value: string }) =>
			url.searchParams.append(entry.key, entry.value),
		);
		const serialized_password = ParameterSerializer.serializeQueryParam(
			{
				name: "password",
				in: "query",
				style: "form",
				explode: true,
				allowReserved: false,
			},
			password,
		);
		serialized_password.forEach((entry: { key: string; value: string }) =>
			url.searchParams.append(entry.key, entry.value),
		);
		const headers: Record<string, string> = {
			...(options?.headers as Record<string, string>),
		};
		const requestOptions:
			| import("node:http").RequestOptions
			| import("node:https").RequestOptions = {
			...options,
			method: "GET",
			headers,
		};
		return new Promise(async (resolve, reject) => {
			const client = url.protocol === "https:" ? https : http;
			const req = client.request(url, requestOptions, (res) => {
				const chunks: Buffer[] = [];
				res.on("data", (chunk) => chunks.push(chunk));
				res.on("end", () => {
					const buffer = Buffer.concat(chunks);
					if (res.statusCode && res.statusCode >= 400) {
						return reject(
							new Error(
								`Request failed: ${res.statusCode} ${res.statusMessage}`,
							),
						);
					}
					try {
						resolve(JSON.parse(buffer.toString("utf-8")));
					} catch (_e) {
						resolve(
							buffer.toString("utf-8") as
								| string
								| number
								| boolean
								| object
								| undefined
								| null as string,
						);
					}
				});
			});
			req.on("error", reject);
			req.end();
		});
	}

	async logoutUser(
		options?: import("node:http").RequestOptions & {
			server?: number | string;
			serverVariables?: Record<string, string>;
		},
	): Promise<string | number | boolean | object | undefined | null> {
		const basePath =
			options?.server !== undefined || options?.serverVariables !== undefined
				? getServerUrl(options?.server ?? 0, options?.serverVariables ?? {})
				: this.basePath;
		const url = new URL(`${basePath}/user/logout`);
		const headers: Record<string, string> = {
			...(options?.headers as Record<string, string>),
		};
		const requestOptions:
			| import("node:http").RequestOptions
			| import("node:https").RequestOptions = {
			...options,
			method: "GET",
			headers,
		};
		return new Promise(async (resolve, reject) => {
			const client = url.protocol === "https:" ? https : http;
			const req = client.request(url, requestOptions, (res) => {
				const chunks: Buffer[] = [];
				res.on("data", (chunk) => chunks.push(chunk));
				res.on("end", () => {
					const buffer = Buffer.concat(chunks);
					if (res.statusCode && res.statusCode >= 400) {
						return reject(
							new Error(
								`Request failed: ${res.statusCode} ${res.statusMessage}`,
							),
						);
					}
					try {
						resolve(JSON.parse(buffer.toString("utf-8")));
					} catch (_e) {
						resolve(
							buffer.toString("utf-8") as
								| string
								| number
								| boolean
								| object
								| undefined
								| null as string | number | boolean | object | undefined | null,
						);
					}
				});
			});
			req.on("error", reject);
			req.end();
		});
	}

	async createUsersWithArrayInput(
		user: User[],
		options?: import("node:http").RequestOptions & {
			server?: number | string;
			serverVariables?: Record<string, string>;
		},
	): Promise<User[]> {
		const basePath =
			options?.server !== undefined || options?.serverVariables !== undefined
				? getServerUrl(options?.server ?? 0, options?.serverVariables ?? {})
				: this.basePath;
		const url = new URL(`${basePath}/user/createWithArray`);
		const headers: Record<string, string> = {
			...(options?.headers as Record<string, string>),
		};
		const requestData = JSON.stringify(user);
		if (!headers["Content-Type"]) {
			headers["Content-Type"] = "application/json";
		}
		if (!headers["Content-Length"]) {
			headers["Content-Length"] = Buffer.byteLength(requestData).toString();
		}
		const requestOptions:
			| import("node:http").RequestOptions
			| import("node:https").RequestOptions = {
			...options,
			method: "POST",
			headers,
		};
		return new Promise(async (resolve, reject) => {
			const client = url.protocol === "https:" ? https : http;
			const req = client.request(url, requestOptions, (res) => {
				const chunks: Buffer[] = [];
				res.on("data", (chunk) => chunks.push(chunk));
				res.on("end", () => {
					const buffer = Buffer.concat(chunks);
					if (res.statusCode && res.statusCode >= 400) {
						return reject(
							new Error(
								`Request failed: ${res.statusCode} ${res.statusMessage}`,
							),
						);
					}
					try {
						resolve(JSON.parse(buffer.toString("utf-8")));
					} catch (_e) {
						resolve(
							buffer.toString("utf-8") as
								| string
								| number
								| boolean
								| object
								| undefined
								| null as User[],
						);
					}
				});
			});
			req.on("error", reject);
			req.write(requestData);
			req.end();
		});
	}

	async createUser(
		user: User,
		options?: import("node:http").RequestOptions & {
			server?: number | string;
			serverVariables?: Record<string, string>;
		},
	): Promise<User> {
		const basePath =
			options?.server !== undefined || options?.serverVariables !== undefined
				? getServerUrl(options?.server ?? 0, options?.serverVariables ?? {})
				: this.basePath;
		const url = new URL(`${basePath}/user`);
		const headers: Record<string, string> = {
			...(options?.headers as Record<string, string>),
		};
		const requestData = JSON.stringify(user);
		if (!headers["Content-Type"]) {
			headers["Content-Type"] = "application/json";
		}
		if (!headers["Content-Length"]) {
			headers["Content-Length"] = Buffer.byteLength(requestData).toString();
		}
		const requestOptions:
			| import("node:http").RequestOptions
			| import("node:https").RequestOptions = {
			...options,
			method: "POST",
			headers,
		};
		return new Promise(async (resolve, reject) => {
			const client = url.protocol === "https:" ? https : http;
			const req = client.request(url, requestOptions, (res) => {
				const chunks: Buffer[] = [];
				res.on("data", (chunk) => chunks.push(chunk));
				res.on("end", () => {
					const buffer = Buffer.concat(chunks);
					if (res.statusCode && res.statusCode >= 400) {
						return reject(
							new Error(
								`Request failed: ${res.statusCode} ${res.statusMessage}`,
							),
						);
					}
					try {
						resolve(JSON.parse(buffer.toString("utf-8")));
					} catch (_e) {
						resolve(
							buffer.toString("utf-8") as
								| string
								| number
								| boolean
								| object
								| undefined
								| null as User,
						);
					}
				});
			});
			req.on("error", reject);
			req.write(requestData);
			req.end();
		});
	}
}

export type GetUserByNameError =
	| string
	| number
	| boolean
	| object
	| undefined
	| null;
export type UpdateUserError =
	| string
	| number
	| boolean
	| object
	| undefined
	| null;
export type DeleteUserError =
	| string
	| number
	| boolean
	| object
	| undefined
	| null;
export type LoginUserError =
	| string
	| number
	| boolean
	| object
	| undefined
	| null;
