import { XmlParser } from "./xml-parser";

// @ts-nocheck
/**
 * This file is generated by a tool. Do not edit directly.
 * Generated by openapi-angular-generator.
 */
export interface ContentDecoderConfig {
	/** If set, parse the string value. 'xml' uses XmlParser, 'json' or true uses JSON.parse. */
	decode?: "json" | "xml" | boolean;
	/** If set, decodes base64/base64url strings to Uint8Array or string for parsing. */
	contentEncoding?: "base64" | "base64url" | string;
	/** Configuration for XmlParser when decode is 'xml'. */
	xmlConfig?: string | number | boolean | object | undefined | null;
	properties?: Record<string, ContentDecoderConfig>;
	items?: ContentDecoderConfig;
}

/** Utility to auto-decode encoded content strings (e.g. JSON or XML embedded in string) based on OAS 3.1 contentSchema. */
export class ContentDecoder {
	private static base64ToBytes(input: string, urlSafe?: boolean): Uint8Array {
		let normalized = input;
		if (urlSafe) {
			normalized = normalized.replace(/-/g, "+").replace(/_/g, "/");
			const pad = normalized.length % 4;
			if (pad === 2) normalized += "==";
			else if (pad === 3) normalized += "=";
		}

		if (
			typeof (
				globalThis as {
					Buffer?: {
						from: (data: string | Uint8Array, encoding?: string) => Uint8Array;
					};
				}
			).Buffer !== "undefined"
		) {
			return Uint8Array.from(
				(
					globalThis as {
						Buffer: { from: (data: string, encoding: string) => Uint8Array };
					}
				).Buffer.from(normalized, "base64"),
			);
		}
		const binary = atob(normalized);
		const bytes = new Uint8Array(binary.length);
		for (let i = 0; i < binary.length; i++) {
			bytes[i] = binary.charCodeAt(i);
		}
		return bytes;
	}

	private static bytesToString(bytes: Uint8Array): string {
		if (typeof TextDecoder !== "undefined") {
			return new TextDecoder().decode(bytes);
		}
		if (
			typeof (
				globalThis as {
					Buffer?: {
						from: (
							data: string | Uint8Array,
							encoding?: string,
						) => { toString: (enc: string) => string };
					};
				}
			).Buffer !== "undefined"
		) {
			return (
				globalThis as {
					Buffer: {
						from: (data: Uint8Array) => { toString: (enc: string) => string };
					};
				}
			).Buffer.from(bytes).toString("utf-8");
		}
		let result = "";
		for (let i = 0; i < bytes.length; i++) {
			result += String.fromCharCode(bytes[i]);
		}
		return result;
	}

	public static decode(
		data: string | number | boolean | object | undefined | null,
		config?: ContentDecoderConfig,
	): string | number | boolean | object | undefined | null {
		if (data === null || data === undefined || !config) {
			return data;
		}

		let current = data;
		if (config.contentEncoding && typeof current === "string") {
			const urlSafe =
				String(config.contentEncoding).toLowerCase() === "base64url";
			const bytes = ContentDecoder.base64ToBytes(current, urlSafe);
			if (config.decode) {
				current = ContentDecoder.bytesToString(bytes);
			} else {
				return bytes;
			}
		}

		// 1. Auto-decode string
		if (config.decode && typeof current === "string") {
			try {
				if (config.decode === "xml") {
					// Use XmlParser for XML content
					return XmlParser.parse(
						current,
						(config.xmlConfig as Record<
							string,
							string | number | boolean | object | undefined | null
						>) || {},
					);
				}

				// Default to JSON parsing
				const parsed = JSON.parse(current);
				// If parsed, we might need to recurse into the parsed structure if deeper config exists
				// (though typically contentSchema is a boundary condition).
				// If properties/items exist in config, apply them to the parsed result.
				if (config.properties || config.items) {
					return ContentDecoder.decode(parsed, { ...config, decode: false });
				}
				return parsed;
			} catch (e) {
				console.warn("Failed to decode contentSchema string", e);
				return current;
			}
		}

		// 2. Arrays
		if (Array.isArray(current) && config.items) {
			return current.map((item) => ContentDecoder.decode(item, config.items));
		}

		// 3. Objects
		if (typeof current === "object") {
			if (config.properties) {
				const result: Record<
					string,
					string | number | boolean | object | undefined | null
				> = { ...current };
				Object.keys(config.properties).forEach((key) => {
					if (Object.hasOwn(current, key)) {
						result[key] = ContentDecoder.decode(
							(
								current as string | number | boolean | object | undefined | null
							)[key],
							config.properties?.[key],
						);
					}
				});
				return result;
			}
		}

		return current;
	}
}
