// @ts-nocheck
/**
* This file is generated by a tool. Do not edit directly.
* Generated by openapi-angular-generator.
*/
export interface ContentEncoderConfig {
    /** If true, stringify the value. */
    encode?: boolean;
    /** Original contentMediaType hint (preserved for round-trip generation). */
    contentMediaType?: string;
    /** If set, encodes the value using base64 or base64url (OAS contentEncoding). */
    contentEncoding?: 'base64' | 'base64url' | string;
    properties?: Record<string, ContentEncoderConfig>;
    items?: ContentEncoderConfig;
}

/** Utility to auto-encode content into strings (e.g. JSON.stringify) based on OAS 3.1 contentMediaType. */
export class ContentEncoder {
    private static stringToBytes(input: string): Uint8Array {

        if (typeof TextEncoder !== 'undefined') {
            return new TextEncoder().encode(input);
        }
        if (typeof (globalThis as string | number | boolean | object | undefined | null).Buffer !== 'undefined') {
            return Uint8Array.from((globalThis as string | number | boolean | object | undefined | null).Buffer.from(input, 'utf-8'));
        }
        const out = new Uint8Array(input.length);
        for (let i = 0; i < input.length; i++) {
            out[i] = input.charCodeAt(i);
        }
        return out;
    }

    private static bytesToBase64(bytes: Uint8Array): string {

        if (typeof (globalThis as string | number | boolean | object | undefined | null).Buffer !== 'undefined') {
            return (globalThis as string | number | boolean | object | undefined | null).Buffer.from(bytes).toString('base64');
        }
        let binary = '';
        for (let i = 0; i < bytes.length; i++) {
            binary += String.fromCharCode(bytes[i]);
        }
        return btoa(binary);
    }

    /** Applies base64/base64url encoding to string or binary values. */
    private static applyContentEncoding(value: string | number | boolean | object | undefined | null, encoding: string): string | number | boolean | object | undefined | null {

        if (value === null || value === undefined) return value;

        const normalized = String(encoding || '').toLowerCase();
        const urlSafe = normalized === 'base64url';
        if (normalized !== 'base64' && normalized !== 'base64url') return value;

        let bytes: Uint8Array | null = null;
        if (value instanceof Uint8Array) {
            bytes = value;
        } else if (value instanceof ArrayBuffer) {
            bytes = new Uint8Array(value);
        } else if (typeof value === 'string') {
            bytes = this.stringToBytes(value);
        } else {
            return value;
        }

        let encoded = this.bytesToBase64(bytes);
        if (urlSafe) {
            encoded = encoded.replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/g, '');
        }
        return encoded;
    }

    public static encode(data: string | number | boolean | object | undefined | null, config?: ContentEncoderConfig): string | number | boolean | object | undefined | null {

        if (data === null || data === undefined || !config) {
            return data;
        }

        // 1. Auto-encode to string
        let current = data;
        if (config.encode && typeof current !== 'string') {
            try {
                current = JSON.stringify(current);
            } catch (e) {
                console.warn('Failed to encode content', e);
            }
        }


        if (config.contentEncoding) {
            const encoded = this.applyContentEncoding(current, config.contentEncoding);
            if (typeof encoded === 'string') {
                return encoded;
            }
        }

        if (config.encode && typeof current === 'string') {
            return current;
        }

        // 2. Arrays
        if (Array.isArray(current) && config.items) {
            return current.map(item => this.encode(item, config.items));
        }

        // 3. Objects
        if (typeof current === 'object') {
            if (config.properties) {
                // Shallow copy to avoid mutating original data if used elsewhere
                const result = { ...current };
                Object.keys(config.properties).forEach(key => {
                    if (Object.prototype.hasOwnProperty.call(current, key)) {
                        result[key] = this.encode((current as string | number | boolean | object | undefined | null)[key], config.properties![key]);
                    }
                });
                return result;
            }
        }

        return current;
    }
}
