// @ts-nocheck
/**
* This file is generated by a tool. Do not edit directly.
* Generated by openapi-angular-generator.
*/
export interface EncodingConfig {
    contentType?: string;
    headers?: Record<string, string>;
    style?: string;
    explode?: boolean;
    allowReserved?: boolean;
    encoding?: Record<string, EncodingConfig>;
    prefixEncoding?: EncodingConfig[];
    itemEncoding?: EncodingConfig;
}

export interface MultipartConfig {
    mediaType?: string;
    encoding?: Record<string, EncodingConfig>;
    prefixEncoding?: EncodingConfig[];
    itemEncoding?: EncodingConfig;
}

export interface MultipartResult {
    content: FormData | Blob;
    headers?: Record<string, string>;
}

/** Utility to build multipart payloads (form-data, mixed, byteranges) with support for OAS 3.2 Array bodies. */
export class MultipartBuilder {
    public static serialize(body: string | number | boolean | object | undefined | null, configInput: MultipartConfig | Record<string, EncodingConfig> = {}): MultipartResult {

        if (body === null || body === undefined) {
            return { content: new FormData() };
        }

        // Normalization: Unify input into MultipartConfig structure
        // Using type guard-like check to detect if input is a config object or a legacy map
        const isConfigObject = configInput &&
            ('encoding' in configInput || 'prefixEncoding' in configInput || 'itemEncoding' in configInput || 'mediaType' in configInput);

        const config: MultipartConfig = isConfigObject
            ? (configInput as MultipartConfig)
            : { encoding: configInput as Record<string, EncodingConfig> };

        if (Array.isArray(body)) {
            // OAS 3.2: Arrays imply positional parts (often multipart/mixed) or simply multiple values without keys.
            // standard FormData cannot represent this without keys, so we default to Manual Blob construction.
            return this.serializeArrayManual(body, config);
        }

        // Check if we can use native FormData or need Manual Blob
        const encodingMap = config.encoding || {};
        const requiresManual = !!config.mediaType || Object.values(encodingMap).some(c =>
            (!!c.headers && Object.keys(c.headers).length > 0) ||
            (!!c.contentType && c.contentType.startsWith('multipart/')) ||
            c.style !== undefined ||
            c.explode !== undefined ||
            c.allowReserved !== undefined ||
            c.prefixEncoding !== undefined ||
            c.itemEncoding !== undefined
        );

        if (requiresManual) {
            return this.serializeObjectManual(body, config);
        }

        return this.serializeNative(body, encodingMap);
    }

    private static serializeNative(body: string | number | boolean | object | undefined | null, encodings: Record<string, EncodingConfig>): MultipartResult {

        const formData = new FormData();

        Object.entries(body).forEach(([key, value]) => {
            if (value === undefined || value === null) return;

            const config = encodings[key] || {};
            const contentType = config.contentType;

            if (Array.isArray(value)) {
                value.forEach(v => this.appendFormData(formData, key, v, contentType));
            } else {
                this.appendFormData(formData, key, value, contentType);
            }
        });

        return { content: formData };
    }

    private static appendFormData(formData: FormData, key: string, value: string | number | boolean | object | undefined | null, contentType?: string) {

        if (value instanceof Blob || value instanceof File) {
            if (value instanceof File) {
                formData.append(key, value, value.name);
            } else {
                formData.append(key, value);
            }
        } else if (contentType === 'application/json' || typeof value === 'object') {
            const blob = new Blob([JSON.stringify(value)], { type: 'application/json' });
            formData.append(key, blob);
        } else {
            formData.append(key, String(value));
        }
    }

    private static serializeObjectManual(body: string | number | boolean | object | undefined | null, config: MultipartConfig): MultipartResult {

        const boundary = this.generateBoundary();
        const parts: Array<string | number | boolean | object | undefined | null> = [];
        const crlf = '\r\n';


        const encodings = config.encoding || {};
        const normalizeStyle = (style?: string) => style || 'form';
        const normalizeExplode = (style: string, explode?: boolean) =>
            explode !== undefined ? explode : style === 'form' || style === 'cookie';
        const getDelimiter = (style: string) => {
            if (style === 'spaceDelimited') return ' ';
            if (style === 'pipeDelimited') return '|';
            if (style === 'tabDelimited') return '\t';
            return ',';
        };
        const serializeArrayValue = (items: Array<string | number | boolean | object | undefined | null>, style: string) =>
            items.map(v => String(v)).join(getDelimiter(style));
        const serializeObjectValue = (obj: Record<string, string | number | boolean | object | undefined | null>, style: string) =>
            Object.entries(obj)
                .map(([k, v]) => `${k}${getDelimiter(style)}${v}`)
                .join(getDelimiter(style));

        Object.entries(body).forEach(([key, value]) => {
            if (value === undefined || value === null) return;

            const itemConfig = encodings[key] || {};
            const hasSerializationHints =
                itemConfig.style !== undefined ||
                itemConfig.explode !== undefined ||
                itemConfig.allowReserved !== undefined;

            if (hasSerializationHints) {
                const style = normalizeStyle(itemConfig.style);
                const explode = normalizeExplode(style, itemConfig.explode);
                const disp = `Content-Disposition: form-data; name="${key}"`;

                if (Array.isArray(value)) {
                    if (explode) {
                        value.forEach(v => {
                            this.appendPart(parts as (string | Blob)[], String(v), { ...itemConfig, contentType: undefined }, boundary, disp);
                        });
                    } else {
                        const serialized = serializeArrayValue(value, style);
                        this.appendPart(parts as (string | Blob)[], serialized, { ...itemConfig, contentType: undefined }, boundary, disp);
                    }
                    return;
                }

                if (typeof value === 'object' && value !== null) {
                    if (explode) {
                        Object.entries(value).forEach(([entryKey, entryValue]) => {
                            const entryDisp = `Content-Disposition: form-data; name="${entryKey}"`;
                            this.appendPart(
                                parts as (string | Blob)[],
                                String(entryValue),
                                { ...itemConfig, contentType: undefined },
                                boundary,
                                entryDisp,
                            );
                        });
                    } else {
                        const serialized = serializeObjectValue(value as Record<string, string | number | boolean | object | undefined | null>, style);
                        this.appendPart(parts as (string | Blob)[], serialized, { ...itemConfig, contentType: undefined }, boundary, disp);
                    }
                    return;
                }


                this.appendPart(parts as (string | Blob)[], String(value), { ...itemConfig, contentType: undefined }, boundary, disp);
                return;
            }

            const values = Array.isArray(value) ? value : [value];
            values.forEach(v => {
                // For Object-based multipart, Content-Disposition is required with a name
                const disp = `Content-Disposition: form-data; name="${key}"`;
                this.appendPart(parts as (string | Blob)[], v, itemConfig, boundary, disp);
            });
        });


        parts.push('--' + boundary + '--' + crlf);

        const mediaType = config.mediaType || 'multipart/form-data';
        const blob = new Blob(parts as (string | Blob)[], { type: mediaType });

        return {
            content: blob,
            headers: { 'Content-Type': `${mediaType}; boundary=${boundary}` }
        };
    }

    private static serializeArrayManual(body: Array<string | number | boolean | object | undefined | null>, config: MultipartConfig): MultipartResult {

        const boundary = this.generateBoundary();
        const parts: Array<string | number | boolean | object | undefined | null> = [];
        const crlf = '\r\n';

        (body as (string | number | boolean | object | null)[]).forEach((item, index) => {
            if (item === undefined || item === null) return;

            // Determine config: prefixEncoding position matches index, fallback to itemEncoding
            let itemConfig: EncodingConfig = {};
            if (config.prefixEncoding && index < config.prefixEncoding.length) {
                itemConfig = config.prefixEncoding[index];
            } else if (config.itemEncoding) {
                itemConfig = config.itemEncoding;
            }

            // For Array-based multipart (mixed), Content-Disposition is usually NOT sent, or sent without name.
            this.appendPart(parts as (string | Blob)[], item, itemConfig, boundary, undefined);
        });


        parts.push('--' + boundary + '--' + crlf);

        // Default to multipart/mixed for arrays unless specified
        const forcedType = config.mediaType || 'multipart/mixed';


        const blob = new Blob(parts as (string | Blob)[], { type: forcedType });

        return {
            content: blob,
            headers: { 'Content-Type': `${forcedType}; boundary=${boundary}` }
        };
    }

    private static appendPart(parts: (string | Blob)[], value: string | number | boolean | object | undefined | null, config: EncodingConfig, boundary: string, defaultDisposition?: string) {

        const crlf = '\r\n';
        let headersStr = '';

        // 1. Content-Disposition
        // Check if headers overrides it
        let disposition = defaultDisposition;

        if (value instanceof File && disposition) {
            disposition += `; filename="${value.name}"`;
        } else if (value instanceof Blob && disposition) {
            disposition += `; filename="blob"`;
        }

        if (config.headers) {
            Object.entries(config.headers).forEach(([hKey, hVal]) => {
                if (hKey.toLowerCase() === 'content-disposition') {
                    disposition = hVal; // Override
                } else {
                    headersStr += `${hKey}: ${hVal}${crlf}`;
                }
            });
        }

        if (disposition) {
            headersStr = `Content-Disposition: ${disposition}${crlf}` + headersStr;
        }

        // 2. Content-Type
        let partContentType = config.contentType;
        if (!partContentType) {
            if (value instanceof Blob) partContentType = value.type || "application/octet-stream";
            else if (typeof value === 'object') partContentType = 'application/json';
            else partContentType = 'text/plain';
        }

        // 3. Value Serialization & Nested Multipart
        let payload: string | Blob | FormData = value;

        if (partContentType && partContentType.includes('multipart')) {
            // Recurse!
            // Check if we have nested Map-based config
            const nestedConfig = config.encoding ? { encoding: config.encoding } : {};

            // We simple pass the inner config we have.
            // Note: we ignore mediaType for nested, allowing default or inferred
            const nestedResult = (Array.isArray(value))
                ? this.serializeArrayManual(value, config as MultipartConfig)
                : this.serializeObjectManual(value, config.encoding ? { encoding: config.encoding } : {});


            payload = nestedResult.content as string | number | boolean | object | undefined | null;

            // Extract boundary from nested result to set content type correctly
            if (nestedResult.headers && nestedResult.headers['Content-Type']) {
                const boundaryMatch = nestedResult.headers['Content-Type'].match(/boundary=(.+)$/);
                const nestedBoundary = boundaryMatch ? boundaryMatch[1] : null;

                if (nestedBoundary) {
                    if (config.contentType) {
                        const baseType = config.contentType.split(';')[0];
                        partContentType = `${baseType}; boundary=${nestedBoundary}`;
                    } else {
                        partContentType = nestedResult.headers['Content-Type'];
                    }
                }
            }
        } else if (typeof value === 'object' && !(value instanceof Blob)) {
            payload = JSON.stringify(value);
        }

        if (partContentType) {
            headersStr += `Content-Type: ${partContentType}${crlf}`;
        }


        parts.push('--' + boundary + crlf + headersStr + crlf);
        parts.push(payload as string | number | boolean | object | undefined | null);
        parts.push(crlf);

    }

    private static generateBoundary(): string {
        return '----' + Math.random().toString(36).substring(2);
    }
}
