// @ts-nocheck
/**
* This file is generated by a tool. Do not edit directly.
* Generated by openapi-angular-generator.
*/
/** Server variable definition (OAS Server Variable Object). */
export interface ServerVariable {
    [key: string]: string | number | boolean | object | undefined | null;
    enum?: string[];
    default: string;
    description?: string;
}

/** Server configuration entries declared in the OpenAPI document. */
export interface ServerConfiguration {
    [key: string]: string | number | boolean | object | undefined | null;
    url: string;
    description?: string;
    name?: string;
    variables?: Record<string, ServerVariable>;
}

/** The list of servers defined in the OpenAPI specification. */
export const API_SERVERS: ServerConfiguration[] = [
    {
        "url": "https://petstore.swagger.io/v2"
    },
    {
        "url": "http://petstore.swagger.io/v2"
    }
];

/** Resolves a server URL from a provided server list. */
/** @param servers The list of servers to resolve against (operation-level or global). */
/** @param indexOrDescription The index of the server, or its name (OAS 3.2), or description. */
/** @param variables A dictionary of variable values (e.g. { port: '8080' }) to override defaults. */
export function resolveServerUrl(servers: ServerConfiguration[], indexOrDescription: number | string = 0, variables?: Record<string, string>): string {
    let server: ServerConfiguration | undefined;
    if (typeof indexOrDescription === 'number') {
        server = servers[indexOrDescription];
    } else {
        server = servers.find(s => s.name === indexOrDescription || s.description === indexOrDescription);
    }
    if (!server) {
        throw new Error(`Server not found: ${indexOrDescription}`);
    }
    let url = server.url;
    if (server.variables) {
        Object.entries(server.variables).forEach(([key, config]) => {
            const value = variables?.[key] ?? config.default;
            if (config.enum && !config.enum.includes(value)) {
                throw new Error(`Value "${value}" for variable "${key}" is not in the allowed enum: ${config.enum.join(', ')}`);
            }
            url = url.replace(new RegExp(`{${key}}`, 'g'), value);
        });
    }
    return url;
}

/** Gets the URL for a specific server definition. */
/** @param indexOrDescription The index of the server, or its name (OAS 3.2), or description. */
/** @param variables A dictionary of variable values (e.g. { port: '8080' }) to override defaults. */
export function getServerUrl(indexOrDescription: number | string = 0, variables?: Record<string, string>): string {
    return resolveServerUrl(API_SERVERS, indexOrDescription, variables);
}
