import type { XmlPropertyConfig } from "./xml-builder";

// @ts-nocheck
/**
 * This file is generated by a tool. Do not edit directly.
 * Generated by openapi-angular-generator.
 */
/** Utility to parse XML responses into typed objects based on OpenAPI metadata (including prefixItems ordering). */
export class XmlParser {
	public static parse(
		xml: string,
		config?: XmlPropertyConfig,
	): string | number | boolean | object | undefined | null {
		if (!xml) return null;
		const parser = new DOMParser();
		const doc = parser.parseFromString(xml, "text/xml");

		const parserError = doc.getElementsByTagName("parsererror");
		if (parserError.length > 0) {
			console.error("XML Parsing Error", parserError[0].textContent);
			return null;
		}

		const root = doc.documentElement;
		return XmlParser.parseNode(root, config || {});
	}

	private static parseNode(
		node: Element,
		config: XmlPropertyConfig,
	): string | number | boolean | object | undefined | null {
		if (
			node.hasAttributeNS("http://www.w3.org/2001/XMLSchema-instance", "nil") &&
			node.getAttributeNS(
				"http://www.w3.org/2001/XMLSchema-instance",
				"nil",
			) === "true"
		) {
			return null;
		}

		const prefixItems = Array.isArray(config.prefixItems)
			? config.prefixItems
			: undefined;
		if (prefixItems && prefixItems.length > 0) {
			const nodes = XmlParser.collectArrayNodes(node);
			const result: Array<
				string | number | boolean | object | undefined | null
			> = [];
			let cursor = 0;

			for (let i = 0; i < prefixItems.length; i++) {
				const cfg = prefixItems[i] || {};
				const child = nodes[cursor];
				if (!child) {
					result.push(undefined);
					continue;
				}
				result.push(XmlParser.parseArrayNode(child, cfg));
				cursor++;
			}

			if (config.items) {
				const itemsConfig = config.items || {};
				for (; cursor < nodes.length; cursor++) {
					const child = nodes[cursor];
					if (
						child.nodeType === 1 &&
						itemsConfig.name &&
						!XmlParser.nodeMatchesName(child as Element, itemsConfig.name)
					) {
						continue;
					}
					result.push(XmlParser.parseArrayNode(child, itemsConfig));
				}
			}
			return result;
		}

		if (config.items || config.wrapped) {
			const itemsConfig = config.items || {};
			const itemName = itemsConfig.name;

			const result: Array<
				string | number | boolean | object | undefined | null
			> = [];
			const children = node.children;

			for (let i = 0; i < children.length; i++) {
				const child = children[i];
				if (!itemName || XmlParser.nodeMatchesName(child, itemName)) {
					result.push(XmlParser.parseNode(child, itemsConfig));
				}
			}
			return result;
		}

		if (config.properties) {
			const result: Record<
				string,
				string | number | boolean | object | undefined | null
			> = {};

			Object.entries(config.properties).forEach(([key, propConfig]) => {
				const nodeType = propConfig.nodeType;

				// OAS 3.2 Support: nodeType 'none' implies the property uses the current node
				// context directly, essentially flattening the structure (e.g. for composition or $ref naming).
				if (nodeType === "none") {
					result[key] = XmlParser.parseNode(node, propConfig);
					return;
				}

				if (propConfig.attribute || nodeType === "attribute") {
					const attrName = propConfig.name || key;
					if (node.hasAttribute(attrName)) {
						result[key] = node.getAttribute(attrName);
					}
					return;
				}

				if (nodeType === "text" || nodeType === "cdata") {
					result[key] = node.textContent;
					return;
				}

				const childTagName = propConfig.name || key;

				if (
					propConfig.items &&
					!propConfig.wrapped &&
					propConfig.nodeType !== "element"
				) {
					const items: Array<
						string | number | boolean | object | undefined | null
					> = [];
					const children = node.children;
					for (let i = 0; i < children.length; i++) {
						if (XmlParser.nodeMatchesName(children[i], childTagName)) {
							items.push(
								XmlParser.parseNode(children[i], propConfig.items || {}),
							);
						}
					}
					result[key] = items;
					return;
				}

				const child = XmlParser.findChild(node, childTagName);
				if (child) {
					result[key] = XmlParser.parseNode(child, propConfig);
				}
			});
			return result;
		}

		return node.textContent;
	}

	private static collectArrayNodes(node: Element): ChildNode[] {
		const nodes = Array.from(node.childNodes);
		return nodes.filter((child) => {
			if (child.nodeType === 1) return true; // Element
			if (child.nodeType === 3 || child.nodeType === 4) {
				return (child.textContent || "").trim().length > 0;
			}
			return false;
		});
	}

	private static parseArrayNode(
		node: ChildNode,
		config: XmlPropertyConfig,
	): string | number | boolean | object | undefined | null {
		if (node.nodeType === 3 || node.nodeType === 4) {
			return node.textContent ?? "";
		}
		return XmlParser.parseNode(node as Element, config);
	}

	private static nodeMatchesName(node: Element, name: string): boolean {
		const local = node.tagName.split(":").pop() || node.tagName;
		return local === name || node.tagName === name;
	}

	private static findChild(
		parent: Element,
		tagName: string,
	): Element | undefined {
		const children = parent.children;
		for (let i = 0; i < children.length; i++) {
			if (XmlParser.nodeMatchesName(children[i], tagName)) {
				return children[i];
			}
		}
		return undefined;
	}
}
