name: Deploy docs to Pages

on:
    push:
        branches: ['master']
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: 'pages'
    cancel-in-progress: false

jobs:
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Checkout ts-morph fork
              uses: actions/checkout@v4
              with:
                  repository: SamuelMarks/ts-morph
                  ref: wasm-typescript-go
                  submodules: false
                  path: ts-morph-tmp

            - name: Checkout typescript-go fork
              uses: actions/checkout@v4
              with:
                  repository: SamuelMarks/typescript-go
                  ref: wasm
                  path: ts-morph-tmp/packages/compiler-go-source

            - name: Move ts-morph to parent dir
              run: |
                  mv ts-morph-tmp ../ts-morph
                  cp -r ts-morph-as ../ts-morph/packages/ts-morph-as
            - name: Setup Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x

            - name: Build ts-morph
              run: cd ../ts-morph && npm install && npm run build:node -w @ts-morph/common && npm run build:node -w ts-morph

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 'lts/*'
            - name: Install requirements
              run: npm ci
            - name: Build docs
              run: npm run docs
            - name: Setup Pages
              uses: actions/configure-pages@v5
              continue-on-error: true
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              continue-on-error: true
              with:
                  path: './docs'
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
              continue-on-error: true
