name: Angular Integration

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    angular-integration:
        runs-on: ubuntu-latest
        services:
            petstore_server:
                image: swaggerapi/petstore
                ports:
                    - '8080:8080'
                env:
                    SWAGGER_HOST: 'http://localhost:8080'
                    SWAGGER_BASE_PATH: '/v2'

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Checkout ts-morph fork
              uses: actions/checkout@v4
              with:
                  repository: SamuelMarks/ts-morph
                  ref: wasm-typescript-go
                  submodules: false
                  path: ts-morph-tmp

            - name: Checkout typescript-go fork
              uses: actions/checkout@v4
              with:
                  repository: SamuelMarks/typescript-go
                  ref: wasm
                  path: ts-morph-tmp/packages/compiler-go-source

            - name: Move ts-morph to parent dir
              run: |
                  mv ts-morph-tmp ../ts-morph
                  cp -r ts-morph-as ../ts-morph/packages/ts-morph-as

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 'lts/*'
                  cache: 'npm'

            - name: Setup Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x

            - name: Build ts-morph
              run: cd ../ts-morph && npm install && npm run build:node -w @ts-morph/common && npm run build:node -w ts-morph

            - name: Install dependencies and build cdd-web-ng
              run: |
                  if [ -f package-lock.json ]; then
                    npm ci
                  else
                    npm i
                  fi
                  npm run build

            - name: Create Angular client
              run: |
                  npx -p @angular/cli ng new angular-client --defaults --skip-git --interactive=false
                  cd angular-client
                  npx ng add @angular/material --skip-confirmation --interactive=false --theme=azure-blue --typography=true --animations=true

            - name: Fetch Petstore JSON
              run: curl --retry 3 --retry-connrefused --retry-delay 2 -fsSL -o petstore.json http://localhost:8080/v2/swagger.json || curl -fsSL -o petstore.json https://petstore.swagger.io/v2/swagger.json

            - name: Run Generator
              run: node dist/cli.js from_openapi to_sdk -i petstore.json --output angular-client/src/app/api

            - name: Run tests for Angular client
              working-directory: angular-client
              run: npm run test -- --watch=false
