name: Publish to npmjs

on:
    release:
        types: [published]

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v6

            - name: Checkout ts-morph fork
              uses: actions/checkout@v6
              with:
                  repository: SamuelMarks/ts-morph
                  ref: wasm-typescript-go
                  submodules: false
                  path: ts-morph-tmp

            - name: Checkout typescript-go fork
              uses: actions/checkout@v6
              with:
                  repository: SamuelMarks/typescript-go
                  ref: wasm
                  path: ts-morph-tmp/packages/compiler-go-source

            - name: Move ts-morph to parent dir
              run: |
                  mv ts-morph-tmp ../ts-morph
                  rm -rf ../ts-morph/packages/ts-morph-as && cp -r ts-morph-as ../ts-morph/packages/ts-morph-as

            - uses: actions/setup-node@v6
              with:
                  node-version: 'lts/*'
                  registry-url: 'https://registry.npmjs.org'

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Setup Go
              uses: actions/setup-go@v6
              with:
                  go-version: '>=1.22.0'
                  cache: true

            - name: Build WASM
              run: |
                  make build_wasm
                  make build_with_ts_go
                  make build_with_ts_go_assemblyscript

            - name: Publish to npmjs
              run: npm publish --provenance --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
